# CDD Tool Configuration
# This file configures the Context-Driven Documentation tool behavior

cdd:
  version: "0.1.0"
  initialized: true

project:
  # Project metadata (auto-detected where possible)
  name: ""
  type: ""  # e.g., "web-app", "api", "library", "cli-tool"

# Tool behavior settings
settings:
  # Automatically detect git root for initialization
  prefer_git_root: true

  # Default ticket type for 'cdd new' command
  default_ticket_type: "feature"

  # Auto-archive completed tickets
  auto_archive: true

# Feature flags
features:
  # Socrates is now a slash command (/socrates) not a CLI command
  # See .claude/commands/socrates.md for the AI-powered implementation
  socrates_slash_command: true

  # Future features
  auto_skills: false
  agent_system: false
